### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by charlesreid1** [dcppc/2018-paper-dcppc#1]
What is the paper's title and/or scope?

Useful reference from @ctb: "Eleven quick tips for architecting biomedical informatics workflows with cloud computing": http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005994

**Comment by raynamharris** [comment]
closed with https://github.com/dcppc/2018-paper-dcppc/commit/d9dc9947c03560e47b1d8445169e6ab31e82f2bf
